import type { FunctionDeclaration } from '@google/genai'

// All search providers funnel into a single SearchResult shape so the
// gallery + store don't need to know about specific domains. Each provider
// adapts its native response to this format.

export type SearchKind =
  | 'music'
  | 'video'
  | 'book'
  | 'movie'
  | 'web'
  | 'place'
  | 'product'
  | 'other'

export interface SearchPreview {
  // 'audio' = HTML5 audio element + play/pause control
  // 'video' = iframe (YouTube embed) or HTML5 video tag
  // 'iframe' = generic embed (Spotify, YouTube fallback, etc.)
  kind: 'audio' | 'video' | 'iframe'
  url: string
}

export interface SearchResult {
  id: string
  kind: SearchKind
  title: string
  // Author / artist / channel / location etc. — secondary line beneath title.
  subtitle?: string
  // Optional richer description (book blurb, video description, etc.).
  description?: string
  imageUrl?: string
  externalUrl?: string
  preview?: SearchPreview
  // Free-form key-value badges shown on the card (year, genre, runtime, …).
  facets?: Record<string, string | number>
  // Why this result matched the query — generated by the provider's scorer.
  reason?: string
}

export interface SearchProvider {
  // Must match the function-declaration name we send to Gemini.
  name: string
  kind: SearchKind
  declaration: FunctionDeclaration
  // Returns at most `limit` results. The args object is whatever Gemini
  // emits for this tool — providers cast it locally.
  handler(args: Record<string, unknown>, limit?: number): Promise<SearchResult[]>
}
